name: Build/Deploy workflow

on:
  push:
    branches: [ '**' ]

  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

    # Build and test services
      - name: Build and test services
        run: make build-all

      - name: Deploy
        run: echo 'Oops...'
